name       : taisei
version    : 1.3.1
release    : 5
homepage   : https://taisei-project.org
source     :
    - https://github.com/taisei-project/taisei/releases/download/v1.3.1/taisei-v1.3.1.tar.xz : 86583a3a710093e63014a5ae6b68251a069cb25ada06c6f8d734f85f31adc985
license    :
    - CC0-1.0
    - CC-BY-4.0
    - MIT
component  : games.arcade
summary    : A free and open-source Touhou Project clone and fangame
description: |
    Taisei is an open clone of the Tōhō Project series. Tōhō is a one-man project of shoot-em-up games set in an isolated world full of Japanese folklore.
builddeps  :
    - pkgconfig(SDL2_mixer)
    - pkgconfig(freetype2)
    - pkgconfig(libwebpdecoder)
    - pkgconfig(libzip)
    - pkgconfig(opusfile)
    - pygments
    - python-docutils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
