name       : taisei
version    : 1.3.2
release    : 9
homepage   : https://taisei-project.org
source     :
    - https://github.com/taisei-project/taisei/releases/download/v1.3.2/taisei-v1.3.2.tar.xz : dbc05f1b5c31981d8711130ac283355b7bfad403895f4096a6bb7e9a3d73a3bc
license    :
    - CC0-1.0
    - CC-BY-4.0
    - MIT
component  : games.arcade
summary    : A free and open-source Touhou Project clone and fangame
description: |
    Taisei is an open clone of the Tōhō Project series. Tōhō is a one-man project of shoot-em-up games set in an isolated world full of Japanese folklore.
builddeps  :
    - pkgconfig(SDL2_mixer)
    - pkgconfig(cglm)
    - pkgconfig(freetype2)
    - pkgconfig(gamemode)
    - pkgconfig(libwebpdecoder)
    - pkgconfig(libzip)
    - pkgconfig(opusfile)
    - pkgconfig(shaderc)
    - python-docutils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
